from aiogram.fsm.state import State, StatesGroup
class UserStates(StatesGroup):
    selecting_language = State()
    selecting_city = State()
    selecting_route = State()
    waiting_payment = State()
    waiting_promo_code = State()
    in_quest = State()
    confirming_photo = State()
    waiting_photo = State()
    waiting_text_answer = State()
    in_settings = State()
class ReviewStates(StatesGroup):
    rating = State()
    text = State()
class QuizStates(StatesGroup):
    answering = State()
class SurveyStates(StatesGroup):
    question_difficulty = State()
    question_navigation = State()
    question_liked = State()
    question_problems = State()
    question_problems_text = State()
    question_improve = State()
class BankStates(StatesGroup):
    main_menu = State()
    waiting_deposit_amount = State()
    waiting_transfer_username = State()
    waiting_transfer_amount = State()
    confirming_transfer = State()
    selecting_city = State()
    selecting_route = State()
class AdminStates(StatesGroup):
    city_menu = State()
    city_add_name = State()
    city_add_description = State()
    city_edit = State()
    route_menu = State()
    route_add_city = State()
    route_add_name = State()
    route_add_description = State()
    route_add_type = State()
    route_add_price = State()
    route_edit = State()
    point_menu = State()
    point_add_route = State()
    point_add_name = State()
    point_add_task = State()
    point_add_fact = State()
    point_add_conditions = State()
    point_add_images = State()
    point_edit = State()
    stats_menu = State()